### ISSUE TITLE
Bravo Troop Training Map, by Lacombe, does not load

### ISSUE THREAD

**Issue by Jaidendude** [7Cav/7thCavalry_Training_Missions#19]
**Description:**
Bravo troop training map V7 on Altis does not load into game.

**Training Map name and version:**
Bravo troop training map V7.Altis

**Steps to reproduce:**
Attempt to load in

**Expected behavior / Requested Solution:**
Allow the map to actually load

**Where did the issue occur?**
Lobby

**Comment by Whitsel** [comment]
Is this version 6_6? I can fix this in a few minutes if you can provide me the mission file

**Comment by longlostblake** [comment]
Working version is already tested & on server, not sure who uploaded. It is removed from this Repo for now.
