### ISSUE TITLE
cScripts error causing equipment loss

### ISSUE THREAD

**Issue by davidcit646** [7Cav/7thCavalry_Training_Missions#23]
Basic Missions currently have an issue where any 'items'  added in cScripts are not being added. This seems to be apparent in the BIT,BLN,BRCC courses but is probably effecting more.

It is probably the version of cScripts we are currently using.

**Comment by longlostblake** [comment]
So far: BIT, BLN & BRRC, AIT.

**Comment by longlostblake** [comment]
Fixed with commit: 08c51b6
