### ISSUE TITLE
TAS_TAS 2.3 updates 

### ISSUE THREAD

**Issue by mackey-a** [7Cav/7thCavalry_Training_Missions#24]
Issue with student invincibility for student and instructor slots for the Basic Airborne Course slots. 
Jump Script is either not functioning properly for DZ Coldblood (Jump #1) or the scripting is wrong for the C130 to control altitude and speed, 280-300m over the ground with an airspeed of 240. 
Jump Script isn't functioning for the 5th Jump out of the CH-47 no idea how to fix that. 

For the Basic Air Assault Course not all the teleporters are functional between the different stations. 

These are all of the currently known issues.

**Comment by longlostblake** [comment]
It currently flies at ~206km/h, altitude of 320m. Will try to adjust.

**Comment by longlostblake** [comment]
closing duplicate
