### ISSUE TITLE
AIT map training server issue

### ISSUE THREAD

**Issue by davidcit646** [7Cav/7thCavalry_Training_Missions#38]
Koehler.M-New AIT MAP-New AIT map would not work and caused about a 30-45 minute delay for the AIT class on 19MAY20 @ 1900

**Comment by longlostblake** [comment]
Will need testing, though im pretty sure it's already been used. For note: This happened last week too when 80% of our servers were broke so i suspect this isnt a mission issue

**Comment by longlostblake** [comment]
Map tested and used for classes. Not S3 issue. Closing.
