### ISSUE TITLE
Alpha Company Training Map - Altis

### ISSUE THREAD

**Issue by TharenR** [7Cav/7thCavalry_Training_Missions#41]
**Map & Version**
Alpha Company Training Map - Altis
Not sure what the latest version is...Alpha_1_7_Training_v4_0_0_LITE.Altis maybe?

**Description:**
After mod pack update, this map does not load (no slots on slot selection screen), so needs to please be updated to work again with new mod pack.

**Steps to reproduce:**
- Join
- Attempt to pick a slot 

**Expected behavior:**
Load in and see the different slots. 

**Where did the issue occur?**
- Lobby

**Additional context:**
None.

**Screenshots:**
None.

**Comment by longlostblake** [comment]
Testing version relased to S6 for uploading. Placing hold until tested.

**Comment by longlostblake** [comment]
Alpha co testing. Awaiting feedback
