### ISSUE TITLE
ACE - FACC Map

### ISSUE THREAD

**Issue by TharenR** [7Cav/7thCavalry_Training_Missions#42]
**Map & Version**
ACE_FACC_v4TEMP.Altis

**Description:**
After new mod pack update, this map does not load. At lobby, no slots.  Not sure if any USAF assets are present or not.

**Where did the issue occur?**
- Lobby

**Comment by longlostblake** [comment]
Reaching out to alpha company

**Comment by longlostblake** [comment]
Uploaded by Geki.
