### ISSUE TITLE
TAS_TAS update request. 

### ISSUE THREAD

**Issue by mackey-a** [7Cav/7thCavalry_Training_Missions#43]
**Map & Version**
TAS_TAS_2.3

**Description:**
Map is going to need an update with the new modpack. Please replace any usaf asset with the RHS C130. 

**Expected behavior:**

**Where did the issue occur?**
- Lobby / Map-Screen / In-Game / Other

**Additional context:**

**Screenshots:**

**Comment by longlostblake** [comment]
duplicate #31
