### ISSUE TITLE
SOI - IHW Map - Altis

### ISSUE THREAD

**Issue by TharenR** [7Cav/7thCavalry_Training_Missions#44]
**Map & Version**
Assuming this is the current version but SOI_IHW_1_2.Altis has slots in the lobby but after you select a slot and load the map, it kicks back to the mission select screen.  Needs to be updated after mod pack update.  Thanks!

**Comment by longlostblake** [comment]
Testing version relased to S6 for uploading. Placing hold until tested.

**Comment by longlostblake** [comment]
Tested, confirmed working.
