### ISSUE TITLE
Removal of old Mission Files for Training Servers

### ISSUE THREAD

**Issue by uaon** [7Cav/7thCavalry_Training_Missions#51]
Currently there are 538 Mission files under /mpmissions for Tarkas Server.
Removal of non-essential or old files is strongly encouraged.

**Comment by uaon** [comment]
[Link](https://1drv.ms/t/s!AgpyQTKa6HjPgZ5Et4y2P5HixHgGHw) for mission file list under /mpmissions as of 7/21/2020

**Comment by uaon** [comment]
- [x] [S3 List](https://gist.github.com/uaon/c1fe4332cc91a88bad26c12f93207c8c)

- [x] S7 List

**Comment by longlostblake** [comment]
I will work on S7 class list.

**Comment by longlostblake** [comment]
> uaon Today at 3:12 PM
> so anyway, they have been sorted already
