### ISSUE TITLE
TAS training map issues

### ISSUE THREAD

**Issue by BurtonPa** [7Cav/7thCavalry_Training_Missions#62]
**Map & Version**
TAS training map (Current)

**Description:**
TAS training map has the following issues:
Chairs are floating or skewed in the classrooms (Hangars)
MFFP C-130 is tilted on its wing
Slides are missing or incorrectly formatte

**Comment by BurtonPa** [comment]
Also, some of the slides for BAAC are mislabeled, example being one-sided Chinook exit showing an example of a 2-sided exit, etc...

**Comment by Whitsel** [comment]
> Chairs are floating or skewed in the classrooms (Hangars)

FWIW without ACEX the chairs mean nothing for now. May incorporate a chair script down the line

Working on the rest now. Will be separating these into separate mission files
