### ISSUE TITLE
TAS and BAAC map issues

### ISSUE THREAD

**Issue by Jaidendude** [7Cav/7thCavalry_Training_Missions#7]
This morning we tried to run a BAAC and had odd issues with the old 1.8 BAAC map, the 2.2 TAS map from whitsel, and the old 1.8 TAS map from Argus.

The 1.8 versions loaded fine, but resulted in odd but consistent crashes from all who tried to connect.

The Whitsel map had no slots.

**Comment by ralphie127** [comment]
- Replaced wooden chairs with plastic chairs.
- Fixed instructors and students placements.
- Adjusted vehicles to be out of the ground.

**Comment by Jaidendude** [comment]
@ralphie127 Has this issue been resolved following the #13 merge?

**Comment by ralphie127** [comment]
Yes, issue has been resolved
